# Generated by Django 2.1.5 on 2023-03-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolnews',
            options={'verbose_name_plural': 'SchoolNews'},
        ),
        migrations.AlterField(
            model_name='schoolnews',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
